In [1]:
import numpy as np
print(np.__version__)

1.21.5


In [10]:
import numpy as np
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [20]:
#2.subscripts
a=np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [21]:
a

array([[10, 20],
       [30, 40]])

In [22]:
print(a[0][0])

10


In [23]:
a[0][0]

10

In [24]:
a[1][0]

30

In [25]:
a[1][1]

40

In [29]:
#3.subscripts
a=np.array([[[10,20],[39,40]],[[29,49],[48,20]]])
a

array([[[10, 20],
        [39, 40]],

       [[29, 49],
        [48, 20]]])

In [30]:
a[1][1][1]

20

In [31]:
a[0][1][1]

40

In [32]:
a[0][1][0]

39

In [33]:
a[1][1][0]

48

In [35]:
a[1][0][1]

49

In [36]:
#floating
a=[10,20,40]
b=np.array(a,dtype=float)
print(b)

[10. 20. 40.]


In [37]:
a=[[10,20],[30,40]]
b=np.array(a,dtype=int,order='c')
print(b)

[[10 20]
 [30 40]]


In [41]:
#initializing arrays
#zeros()
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [44]:
a=np.zeros([2,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
a=np.zeros([2,3,4])
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
#full()
a=np.full([2,3],1)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [49]:
a=np.full([4,2],11)
a

array([[11, 11],
       [11, 11],
       [11, 11],
       [11, 11]])

In [50]:
#random.rand()
a=np.random.rand(2,3)
a

array([[0.29309806, 0.96726234, 0.99431929],
       [0.7324492 , 0.16789464, 0.42395833]])

In [51]:
#ones()
a=np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
#eye() ----> diagonal elements are one all are zeroes
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
#numerical ranges
#arange
a=np.arange(10,20,1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
a=np.arange(19,299,12)
a

array([ 19,  31,  43,  55,  67,  79,  91, 103, 115, 127, 139, 151, 163,
       175, 187, 199, 211, 223, 235, 247, 259, 271, 283, 295])

In [60]:
a=np.arange(10,70,5,dtype=float)
a

array([10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65.])

In [79]:
#reshape
a=np.arange(10,70,10)
print(a)

[10 20 30 40 50 60]


In [80]:
a.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [69]:
a.reshape(1,6)

array([[10, 20, 30, 40, 50, 60]])

In [71]:
a.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [72]:
a.reshape(6,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [74]:
a.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [83]:
#linspace
#linspace(start_size,stop_size,step_size,endpoint=False/True)
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [84]:
np.linspace(10,100,10,endpoint=False)

array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])

In [86]:
np.linspace(10,100,10,endpoint=False,retstep=True)

(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)

In [87]:
np.linspace(10,100,10,endpoint=False,retstep=True,dtype=int)

(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)

In [88]:
#logspace()
np.logspace(1,10,10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [89]:
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [104]:
#Array properities
a=np.arange(10,100,10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [105]:
a.reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [106]:
#1.size---> np.size(array)
np.size(a)

9

In [108]:
#2.shape---> np.shape(array)
np.shape(a)   #o/p is (3,3)

(9,)

In [109]:
#3.dtype----> np.dtype(array)
a.dtype

dtype('int32')

In [113]:
b=np.array([10,20,20],dtype=float)
b

array([10., 20., 20.])

In [114]:
b.dtype

dtype('float64')

In [116]:
#Array functions
#Accessing and slicing operations
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [117]:
#accessing
a[1]

array([40, 50, 60])

In [118]:
a[1][0]

40

In [119]:
a[1]

array([40, 50, 60])

In [120]:
a[0][2]

30

In [121]:
s=np.arange(10,100,10)
s

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [122]:
#slicing
s[2:6]

array([30, 40, 50, 60])

In [123]:
#copy
b=np.copy(a)
b

array([[10, 20, 30],
       [40, 50, 60]])

In [127]:
a,b

(array([[10, 20, 30],
        [40, 50, 60]]),
 array([[10, 20, 30],
        [40, 50, 60]]))

In [129]:
#view
c=b.view()
c

array([[10, 20, 30],
       [40, 50, 60]])

In [130]:
print('a=',a)
print('b=',b)
print('c=',c)

a= [[10 20 30]
 [40 50 60]]
b= [[10 20 30]
 [40 50 60]]
c= [[10 20 30]
 [40 50 60]]


In [131]:
a[0][1]

20

In [132]:
c[1][2]

60

In [133]:
b[1][1]

50

In [136]:
#sort()
a=np.array([30,40,15,3,10,45])
np.sort(a)

array([ 3, 10, 15, 30, 40, 45])

In [137]:
#reshape()
a=a.reshape(2,3)
a

array([[30, 40, 15],
       [ 3, 10, 45]])

In [142]:
a=a.reshape(3,2)
a

array([[30, 40],
       [15,  3],
       [10, 45]])

In [143]:
np.sort(a,axis=0)

array([[10,  3],
       [15, 40],
       [30, 45]])

In [144]:
np.sort(a)

array([[30, 40],
       [ 3, 15],
       [10, 45]])

In [145]:
#append
a=np.array([10,20,30])
b=np.array([40,50,60])
np.append(a,b)

array([10, 20, 30, 40, 50, 60])

In [146]:
a=np.array([[10,20],[30,40]])
b=np.array([[50,60],[70,80]])
np.append(a,b)

array([10, 20, 30, 40, 50, 60, 70, 80])

In [147]:
#insert
np.insert(a,3,(35,45))

array([10, 20, 30, 35, 45, 40])

In [148]:
np.insert(a,3,(35,45)).reshape(2,3)

array([[10, 20, 30],
       [35, 45, 40]])

In [151]:
#delete
np.delete(a,2)

array([10, 20, 40])

In [152]:
a

array([[10, 20],
       [30, 40]])

In [153]:
#concatenate
np.concatenate((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [154]:
#stack
np.stack((a,b))

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [156]:
#vstack-----> vertical stack
np.vstack((a,b))

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [157]:
#hstack---->horizontal stack
np.hstack((a,b))

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [158]:
#dstack----> diagonal stack
np.dstack((a,b))

array([[[10, 50],
        [20, 60]],

       [[30, 70],
        [40, 80]]])

In [159]:
#split
x=np.arange(10,110,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [162]:
np.split(x,2)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]

In [163]:
np.split(x,5)

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

In [164]:
np.split(x,(2,6))

[array([10, 20]), array([30, 40, 50, 60]), array([ 70,  80,  90, 100])]

In [166]:
z=np.split(x,5)
z

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

In [167]:
print(z)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([ 90, 100])]


In [170]:
s1,s2,s3,s4,s5=np.split(x,5)

In [171]:
s1

array([10, 20])

In [172]:
s2

array([30, 40])

In [173]:
s3

array([50, 60])

In [174]:
s4

array([70, 80])

In [175]:
s5

array([ 90, 100])

In [176]:
#where
a

array([[10, 20],
       [30, 40]])

In [178]:
a=np.arange(10,130,10).reshape(4,3)
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [179]:
np.where(a==80)

(array([2], dtype=int64), array([1], dtype=int64))

In [181]:
n=np.arange(10,100,20)
n

array([10, 30, 50, 70, 90])

In [182]:
np.where(b==50)

(array([0], dtype=int64), array([0], dtype=int64))

In [183]:
a

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [184]:
np.where(a%20==0)

(array([0, 1, 1, 2, 3, 3], dtype=int64),
 array([1, 0, 2, 1, 0, 2], dtype=int64))

In [185]:
#searchsorted
a=np.array([10,20,30,40,50,60])
np.searchsorted(a,40)

3

In [186]:
np.searchsorted(a,50)

4

In [187]:
np.searchsorted(a,[40,50])

array([3, 4], dtype=int64)

In [188]:
np.searchsorted(a,[30,40,50])

array([2, 3, 4], dtype=int64)

In [189]:
#Arithmetic Operations
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[1,2,3],[4,5,6]])

In [190]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [191]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [192]:
#add()
np.add(a,b)

array([[11, 22, 33],
       [44, 55, 66]])

In [194]:
#subtact()
np.subtract(a,b)

array([[ 9, 18, 27],
       [36, 45, 54]])

In [195]:
#multiply()
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 360]])

In [196]:
#divide()
np.divide(a,b)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [197]:
#exp()
np.exp(a)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26]])

In [198]:
np.exp(b)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [199]:
#sqrt()
np.sqrt(a)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669]])

In [200]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [202]:
b[1][0]=40
b[1][1]=50
b[1][2]=60
b

array([[ 1, 40,  3],
       [40, 50, 60]])

In [203]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [205]:
#comparsion
np.array_equal(a,b)

False

In [206]:
b[0][0]=10
b[0][1]=20
b[0][2]=30
b

array([[10, 20, 30],
       [40, 50, 60]])

In [207]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [208]:
np.array_equal(a,b)

True

In [212]:
#Array functions
a=np.array([[10,20],[30,40],[50,60]])
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [213]:
#sum
np.sum(a)

210

In [217]:
np.sum(a,axis=0)

array([ 90, 120])

In [214]:
#min()
np.min(a)

10

In [215]:
#max()
np.max(a)

60

In [216]:
#mean()
np.mean(a)

35.0

In [222]:
np.mean(a,axis=0)

array([30., 40.])

In [221]:
np.mean(a,axis=1)

array([15., 35., 55.])

In [223]:
np.max(a,axis=0)

array([50, 60])

In [218]:
#median
np.median(a)

35.0

In [219]:
np.median(a,axis=0)

array([30., 40.])

In [220]:
np.median(a,axis=1)

array([15., 35., 55.])

In [224]:
#var---->varience
np.var(a)

291.6666666666667

In [225]:
np.var(a,axis=1)

array([25., 25., 25.])

In [226]:
np.var(a,axis=0)

array([266.66666667, 266.66666667])

In [227]:
#std---->standard deviation
np.std(a)

17.07825127659933

In [228]:
np.std(a,axis=0)

array([16.32993162, 16.32993162])

In [229]:
np.std(a,axis=1)

array([5., 5., 5.])