In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt
import seaborn as sn
import warnings 
warnings.filterwarnings('ignore')

In [31]:
df=pd.read_csv('sonar_dataset.csv')
df.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  

[5 rows x 61 columns]

In [32]:
df.shape

(207, 61)

In [33]:
df.isna().sum().sum()

0

In [34]:
df.columns

Index(['0.0200', '0.0371', '0.0428', '0.0207', '0.0954', '0.0986', '0.1539',
       '0.1601', '0.3109', '0.2111', '0.1609', '0.1582', '0.2238', '0.0645',
       '0.0660', '0.2273', '0.3100', '0.2999', '0.5078', '0.4797', '0.5783',
       '0.5071', '0.4328', '0.5550', '0.6711', '0.6415', '0.7104', '0.8080',
       '0.6791', '0.3857', '0.1307', '0.2604', '0.5121', '0.7547', '0.8537',
       '0.8507', '0.6692', '0.6097', '0.4943', '0.2744', '0.0510', '0.2834',
       '0.2825', '0.4256', '0.2641', '0.1386', '0.1051', '0.1343', '0.0383',
       '0.0324', '0.0232', '0.0027', '0.0065', '0.0159', '0.0072', '0.0167',
       '0.0180', '0.0084', '0.0090', '0.0032', 'R'],
      dtype='object')

In [36]:
df['R'].value_counts()

M    111
R     96
Name: R, dtype: int64

In [37]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1:]
x.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  \
0  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
1  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
2  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
3  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
4  0.3039  ...  0.0104  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057   

   0.0084  0.0090  0.0032  
0  0.0049  0.0052  0.0044  
1  0.0164  0.0095  0.0078  
2  0.0044  0.0040  0.0117  
3  0.0048  0.0107  0.0094  
4  0.0027  0.0051  0.0062  

[5 rows x 60 columns]

In [38]:
y

R
0    R
1    R
2    R
3    R
4    R
..  ..
202  M
203  M
204  M
205  M
206  M

[207 rows x 1 columns]

In [39]:
y=pd.get_dummies(y,drop_first=True)
y.head()

R_R
0    1
1    1
2    1
3    1
4    1

In [40]:
y.value_counts()

R_R
0      111
1       96
dtype: int64

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [42]:
print(x_train.size)
print(x_train.shape)
x_train.head()

9300
(155, 60)


0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
67   0.0195  0.0142  0.0181  0.0406  0.0391  0.0249  0.0892  0.0973  0.0840   
14   0.0298  0.0615  0.0650  0.0921  0.1615  0.2294  0.2176  0.2033  0.1459   
164  0.0221  0.0065  0.0164  0.0487  0.0519  0.0849  0.0812  0.1833  0.2228   
179  0.0310  0.0221  0.0433  0.0191  0.0964  0.1827  0.1106  0.1702  0.2804   
19   0.0473  0.0509  0.0819  0.1252  0.1783  0.3070  0.3008  0.2362  0.3830   

     0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  \
67   0.1191  ...  0.0125  0.0028  0.0067  0.0120  0.0012  0.0022  0.0058   
14   0.0852  ...  0.0154  0.0031  0.0153  0.0071  0.0212  0.0076  0.0152   
164  0.1810  ...  0.0167  0.0089  0.0051  0.0015  0.0075  0.0058  0.0016   
179  0.4432  ...  0.0249  0.0204  0.0059  0.0053  0.0079  0.0037  0.0015   
19   0.3759  ...  0.0107  0.0193  0.0118  0.0064  0.0042  0.0054  0.0049   

     0.0084  0.0090  0.0032  
67   0.0042  0.0067  0.0012  
14   0.0049  0.0200  0.0073  
164  0.0070  0.0074  0.0038  
179  0.0056  0.0067  0.0054  
19   0.0082  0.0028  0.0027  

[5 rows x 60 columns]

In [43]:
print(x_train.shape)
print(x_test.size)
x_test.head()

(155, 60)
3120


0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
186  0.0368  0.0279  0.0103  0.0566  0.0759  0.0679  0.0970  0.1473  0.2164   
155  0.0047  0.0059  0.0080  0.0554  0.0883  0.1278  0.1674  0.1373  0.2922   
165  0.0411  0.0277  0.0604  0.0525  0.0489  0.0385  0.0611  0.1117  0.1237   
200  0.0335  0.0258  0.0398  0.0570  0.0529  0.1091  0.1709  0.1684  0.1865   
58   0.0125  0.0152  0.0218  0.0175  0.0362  0.0696  0.0873  0.0616  0.1252   

     0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  \
186  0.2544  ...  0.0151  0.0105  0.0024  0.0018  0.0057  0.0092  0.0009   
155  0.3469  ...  0.0129  0.0095  0.0126  0.0069  0.0039  0.0068  0.0060   
165  0.2300  ...  0.0181  0.0217  0.0038  0.0019  0.0065  0.0132  0.0108   
200  0.2660  ...  0.0130  0.0120  0.0039  0.0053  0.0062  0.0046  0.0045   
58   0.1302  ...  0.0019  0.0041  0.0074  0.0030  0.0050  0.0048  0.0017   

     0.0084  0.0090  0.0032  
186  0.0086  0.0110  0.0052  
155  0.0045  0.0002  0.0029  
165  0.0050  0.0085  0.0044  
200  0.0022  0.0005  0.0031  
58   0.0041  0.0086  0.0058  

[5 rows x 60 columns]

In [44]:
print(y_train.shape)
print(y_train.size)
y_train.head()

(155, 1)
155


R_R
67     1
14     1
164    0
179    0
19     1

In [45]:
print(y_test.shape)
print(y_test.size)
y_test.head()

(52, 1)
52


R_R
186    0
155    0
165    0
200    0
58     1

In [46]:
import tensorflow as tf
from tensorflow import keras

In [47]:
model=keras.Sequential([
    keras.layers.Dense(60,input_dim=60,activation='relu'),
    keras.layers.Dense(30,activation='relu'),
    keras.layers.Dense(15,activation='relu'),
    keras.layers.Dense(1,activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=100,batch_size=8)

Epoch 1/100
20/20 [==============================] - 2s 5ms/step - loss: 0.6875 - accuracy: 0.5355
Epoch 2/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6694 - accuracy: 0.6387
Epoch 3/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6478 - accuracy: 0.6581
Epoch 4/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6192 - accuracy: 0.7161
Epoch 5/100
20/20 [==============================] - 0s 5ms/step - loss: 0.5952 - accuracy: 0.7484
Epoch 6/100
20/20 [==============================] - 0s 5ms/step - loss: 0.5581 - accuracy: 0.7419
Epoch 7/100
20/20 [==============================] - 0s 5ms/step - loss: 0.5364 - accuracy: 0.7548
Epoch 8/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4930 - accuracy: 0.7935
Epoch 9/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4772 - accuracy: 0.7548
Epoch 10/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4560 - accuracy: 0.8000
Epoch 11/

20/20 [==============================] - 0s 5ms/step - loss: 0.0128 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0095 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0080 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0081 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0080 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0098 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0084 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0061 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0060 - accuracy: 1.0000
Epoch 92/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0061 - accuracy: 1.0000
Epoch 93/100


In [48]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 13ms/step - loss: 0.6144 - accuracy: 0.8846


[0.6143864393234253, 0.8846153616905212]

In [52]:
model.predict(x_test)

2/2 [==============================] - 0s 3ms/step


array([[3.5513108e-04],
       [4.1216288e-05],
       [4.6611219e-03],
       [3.2262687e-04],
       [9.9999702e-01],
       [1.8963896e-02],
       [7.2040802e-01],
       [3.3584016e-04],
       [3.1725434e-04],
       [9.9992299e-01],
       [9.9999374e-01],
       [9.2336816e-01],
       [2.8922182e-04],
       [2.4857871e-02],
       [3.2215644e-02],
       [4.6431541e-01],
       [9.9990720e-01],
       [8.3365157e-04],
       [9.8915631e-01],
       [9.9999934e-01],
       [6.2595311e-05],
       [9.9992073e-01],
       [9.3924022e-01],
       [8.2147149e-03],
       [2.1014361e-02],
       [1.2995286e-02],
       [9.9928689e-01],
       [9.5974880e-01],
       [9.8336571e-01],
       [3.2358575e-03],
       [1.3004717e-01],
       [9.8730206e-06],
       [9.8287165e-01],
       [7.8696635e-04],
       [9.9995923e-01],
       [8.1764483e-01],
       [9.9988890e-01],
       [6.9200699e-03],
       [9.9869078e-01],
       [6.2863894e-02],
       [1.2270654e-01],
       [6.851331

In [53]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test loss: {loss}, Test accuracy: {accuracy}")

2/2 [==============================] - 0s 7ms/step - loss: 0.6144 - accuracy: 0.8846
Test loss: 0.6143864393234253, Test accuracy: 0.8846153616905212


In [54]:
predictions = model.predict(x)
print(predictions)

7/7 [==============================] - 0s 3ms/step
[[9.98827159e-01]
 [9.97621596e-01]
 [9.99878764e-01]
 [9.96441543e-01]
 [9.99993742e-01]
 [9.98544514e-01]
 [9.78879571e-01]
 [9.89764988e-01]
 [9.95766819e-01]
 [9.99930680e-01]
 [9.99961436e-01]
 [8.21471494e-03]
 [9.98311341e-01]
 [9.98713911e-01]
 [9.96888101e-01]
 [9.84594882e-01]
 [7.86966353e-04]
 [9.99999702e-01]
 [3.35840159e-04]
 [9.84619498e-01]
 [9.99729633e-01]
 [9.97264862e-01]
 [9.99983251e-01]
 [9.99991655e-01]
 [9.99476314e-01]
 [9.33870792e-01]
 [9.85263884e-01]
 [6.92006992e-03]
 [9.82871652e-01]
 [9.39240217e-01]
 [9.99835908e-01]
 [9.99907196e-01]
 [9.80328977e-01]
 [9.89156306e-01]
 [1.89638957e-02]
 [9.99286890e-01]
 [9.99667883e-01]
 [9.98616874e-01]
 [9.99888897e-01]
 [9.98788893e-01]
 [9.99999344e-01]
 [1.00000000e+00]
 [9.99982059e-01]
 [9.99731719e-01]
 [9.59748805e-01]
 [9.88854051e-01]
 [9.83306766e-01]
 [9.23368156e-01]
 [9.95190978e-01]
 [9.99998331e-01]
 [9.99999762e-01]
 [9.83365715e-01]
 [9.99915361e

In [55]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

In [56]:
model = Sequential()
model.add(Dense(4, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=1000, batch_size=4)

Epoch 1/1000
1/1 [==============================] - 1s 1s/step - loss: 0.7095 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.7090 - accuracy: 0.2500
Epoch 3/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.7085 - accuracy: 0.2500
Epoch 4/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.7081 - accuracy: 0.2500
Epoch 5/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.7076 - accuracy: 0.2500
Epoch 6/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.7071 - accuracy: 0.2500
Epoch 7/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.7066 - accuracy: 0.2500
Epoch 8/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.7061 - accuracy: 0.2500
Epoch 9/1000
1/1 [==============================] - 0s 18ms/step - loss: 0.7057 - accuracy: 0.2500
Epoch 10/1000
1/1 [==============================] - 0s 19ms/step - loss: 0.7052 - accuracy: 0.2500
Epoch 11/10

1/1 [==============================] - 0s 15ms/step - loss: 0.6799 - accuracy: 0.5000
Epoch 84/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6796 - accuracy: 0.5000
Epoch 85/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.6793 - accuracy: 0.5000
Epoch 86/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.6791 - accuracy: 0.5000
Epoch 87/1000
1/1 [==============================] - 0s 18ms/step - loss: 0.6788 - accuracy: 0.5000
Epoch 88/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6786 - accuracy: 0.5000
Epoch 89/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.6783 - accuracy: 0.5000
Epoch 90/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.6781 - accuracy: 0.5000
Epoch 91/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.6778 - accuracy: 0.5000
Epoch 92/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6776 - accuracy: 0.5000
Epoch 93/1000


1/1 [==============================] - 0s 14ms/step - loss: 0.6438 - accuracy: 0.7500
Epoch 246/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.6435 - accuracy: 0.7500
Epoch 247/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6433 - accuracy: 0.7500
Epoch 248/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.6431 - accuracy: 0.7500
Epoch 249/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.6428 - accuracy: 0.7500
Epoch 250/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.6426 - accuracy: 0.7500
Epoch 251/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6424 - accuracy: 0.7500
Epoch 252/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.6421 - accuracy: 0.7500
Epoch 253/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.6418 - accuracy: 0.7500
Epoch 254/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.6416 - accuracy: 0.7500
Epoch

1/1 [==============================] - 0s 14ms/step - loss: 0.6023 - accuracy: 0.7500
Epoch 408/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6021 - accuracy: 0.7500
Epoch 409/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.6018 - accuracy: 0.7500
Epoch 410/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.6016 - accuracy: 0.7500
Epoch 411/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.6013 - accuracy: 0.7500
Epoch 412/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.6010 - accuracy: 0.7500
Epoch 413/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.6008 - accuracy: 0.7500
Epoch 414/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.6005 - accuracy: 0.7500
Epoch 415/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.6003 - accuracy: 0.7500
Epoch 416/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.6000 - accuracy: 0.7500
Epoch

1/1 [==============================] - 0s 14ms/step - loss: 0.5592 - accuracy: 0.7500
Epoch 570/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.5589 - accuracy: 0.7500
Epoch 571/1000
1/1 [==============================] - 0s 19ms/step - loss: 0.5586 - accuracy: 0.7500
Epoch 572/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.5584 - accuracy: 0.7500
Epoch 573/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.5581 - accuracy: 0.7500
Epoch 574/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.5579 - accuracy: 0.7500
Epoch 575/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.5576 - accuracy: 0.7500
Epoch 576/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.5573 - accuracy: 0.7500
Epoch 577/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.5571 - accuracy: 0.7500
Epoch 578/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.5568 - accuracy: 0.7500
Epoch

1/1 [==============================] - 0s 17ms/step - loss: 0.5179 - accuracy: 0.7500
Epoch 732/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.5176 - accuracy: 0.7500
Epoch 733/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.5173 - accuracy: 0.7500
Epoch 734/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.5172 - accuracy: 0.7500
Epoch 735/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.5169 - accuracy: 0.7500
Epoch 736/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.5167 - accuracy: 0.7500
Epoch 737/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.5165 - accuracy: 0.7500
Epoch 738/1000
1/1 [==============================] - 0s 12ms/step - loss: 0.5162 - accuracy: 0.7500
Epoch 739/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.5160 - accuracy: 0.7500
Epoch 740/1000
1/1 [==============================] - 0s 13ms/step - loss: 0.5157 - accuracy: 0.7500
Epoch

1/1 [==============================] - 0s 15ms/step - loss: 0.4820 - accuracy: 0.7500
Epoch 894/1000
1/1 [==============================] - 0s 18ms/step - loss: 0.4818 - accuracy: 0.7500
Epoch 895/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.4816 - accuracy: 0.7500
Epoch 896/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.4814 - accuracy: 0.7500
Epoch 897/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.4812 - accuracy: 0.7500
Epoch 898/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.4809 - accuracy: 0.7500
Epoch 899/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.4808 - accuracy: 0.7500
Epoch 900/1000
1/1 [==============================] - 0s 18ms/step - loss: 0.4806 - accuracy: 0.7500
Epoch 901/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.4804 - accuracy: 0.7500
Epoch 902/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.4802 - accuracy: 0.7500
Epoch

In [24]:
model.evaluate(X,y)

1/1 [==============================] - 0s 377ms/step - loss: 0.2761 - accuracy: 1.0000


[0.2761172950267792, 1.0]

In [25]:
scores = model.evaluate(X, y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

1/1 [==============================] - 0s 71ms/step - loss: 0.2761 - accuracy: 1.0000

accuracy: 100.00%


In [26]:
predictions = model.predict(X)
print(predictions)

1/1 [==============================] - 0s 137ms/step
[[0.3019791]
 [0.8175763]
 [0.8318978]
 [0.3019791]]


In [59]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
#dir(datasets)

In [60]:
df=load_iris()
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [63]:
x=pd.DataFrame(data=df.data,columns=df.feature_names)
y=pd.Series(data=df.target)
y.head()

0    0
1    0
2    0
3    0
4    0
dtype: int32

In [65]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [66]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [67]:
print(x_train.shape)
print(x_train.size)
x_train.head()

(120, 4)
480


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
137                6.4               3.1                5.5               1.8
84                 5.4               3.0                4.5               1.5
27                 5.2               3.5                1.5               0.2
127                6.1               3.0                4.9               1.8
132                6.4               2.8                5.6               2.2

In [68]:
print(x_test.shape)
print(x_test.size)
x_test.head()

(30, 4)
120


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
114                5.8               2.8                5.1               2.4
62                 6.0               2.2                4.0               1.0
33                 5.5               4.2                1.4               0.2
107                7.3               2.9                6.3               1.8
7                  5.0               3.4                1.5               0.2

In [69]:
print(y_train.shape)
print(y_train.size)
y_train.head()

(120,)
120


137    2
84     1
27     0
127    2
132    2
dtype: int32

In [70]:
print(y_test.shape)
print(y_test.size)
y_test.head()

(30,)
30


114    2
62     1
33     0
107    2
7      0
dtype: int32

In [71]:
model=Sequential()
model.add(Dense(60,input_dim=4,activation='relu'))
model.add(Dense(30,activation='relu'))
model.add(Dense(15,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=100,batch_size=4)

Epoch 1/100
30/30 [==============================] - 2s 4ms/step - loss: 0.1016 - accuracy: 0.3083
Epoch 2/100
30/30 [==============================] - 0s 3ms/step - loss: -0.6548 - accuracy: 0.3083
Epoch 3/100
30/30 [==============================] - 0s 3ms/step - loss: -1.4140 - accuracy: 0.3083
Epoch 4/100
30/30 [==============================] - 0s 3ms/step - loss: -2.5490 - accuracy: 0.3083
Epoch 5/100
30/30 [==============================] - 0s 3ms/step - loss: -5.3132 - accuracy: 0.3083
Epoch 6/100
30/30 [==============================] - 0s 3ms/step - loss: -10.1594 - accuracy: 0.3083
Epoch 7/100
30/30 [==============================] - 0s 3ms/step - loss: -19.8436 - accuracy: 0.3083
Epoch 8/100
30/30 [==============================] - 0s 3ms/step - loss: -35.4559 - accuracy: 0.3083
Epoch 9/100
30/30 [==============================] - 0s 3ms/step - loss: -61.4047 - accuracy: 0.3083
Epoch 10/100
30/30 [==============================] - 0s 3ms/step - loss: -106.5515 - accuracy: 0

In [73]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 289ms/step - loss: -431262.6250 - accuracy: 0.4333


[-431262.625, 0.4333333373069763]

In [74]:
model.predict(x_test)

1/1 [==============================] - 0s 112ms/step


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [77]:
loss,accuracy=model.evaluate(x_test,y_test)
print(f'Test Loss:{loss}  Accuracy:{accuracy}')
print('Accuracy is:',accuracy*100)

1/1 [==============================] - 0s 38ms/step - loss: -431262.6250 - accuracy: 0.4333
Test Loss:-431262.625   Accuracy:0.4333333373069763
Accuracy is: 43.33333373069763


In [78]:
pred=model.predict(x_test)
print(pred)

1/1 [==============================] - 0s 31ms/step
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [93]:
import tensorflow_datasets as tfds
dataset_names = tfds.list_builders()
print("Keras inbuilt datasets:")
for dataset_name in dataset_names:
    print("- " + dataset_name)

Keras inbuilt datasets:
- abstract_reasoning
- accentdb
- aeslc
- aflw2k3d
- ag_news_subset
- ai2_arc
- ai2_arc_with_ir
- amazon_us_reviews
- anli
- answer_equivalence
- arc
- asqa
- asset
- assin2
- bair_robot_pushing_small
- bccd
- beans
- bee_dataset
- beir
- big_patent
- bigearthnet
- billsum
- binarized_mnist
- binary_alpha_digits
- ble_wind_field
- blimp
- booksum
- bool_q
- bucc
- c4
- c4_wsrs
- caltech101
- caltech_birds2010
- caltech_birds2011
- cardiotox
- cars196
- cassava
- cats_vs_dogs
- celeb_a
- celeb_a_hq
- cfq
- cherry_blossoms
- chexpert
- cifar10
- cifar100
- cifar100_n
- cifar10_1
- cifar10_corrupted
- cifar10_n
- citrus_leaves
- cityscapes
- civil_comments
- clevr
- clic
- clinc_oos
- cmaterdb
- cnn_dailymail
- coco
- coco_captions
- coil100
- colorectal_histology
- colorectal_histology_large
- common_voice
- conll2002
- conll2003
- controlled_noisy_web_labels
- coqa
- cos_e
- cosmos_qa
- covid19
- covid19sum
- crema_d
- criteo
- cs_restaurants
- curated_breast_ima

In [106]:
from keras.datasets import boston_housing
(x_train,y_train),(x_test,y_test)=boston_housing.load_data()

57026/57026 [==============================] - 0s 1us/step


In [109]:
print(x_train.shape)
print(x_train.size)
x_train

(404, 13)
5252


array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
        3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.75520e+02, 3.26000e+00],
       ...,
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.61950e+02, 1.57900e+01],
       [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
        3.76700e+02, 4.38000e+00]])

In [110]:
print(x_test.shape)
print(x_test.size)
x_test

(102, 13)
1326


array([[1.80846e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        2.72500e+01, 2.90500e+01],
       [1.23290e-01, 0.00000e+00, 1.00100e+01, ..., 1.78000e+01,
        3.94950e+02, 1.62100e+01],
       [5.49700e-02, 0.00000e+00, 5.19000e+00, ..., 2.02000e+01,
        3.96900e+02, 9.74000e+00],
       ...,
       [1.83377e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.89610e+02, 1.92000e+00],
       [3.58090e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.91700e+02, 9.71000e+00],
       [2.92400e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.40160e+02, 9.81000e+00]])

In [111]:
print(y_train.shape)
print(y_train.size)
y_train

(404,)
404


array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
       17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
       32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
       23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
       12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
       22. , 14.5, 11. , 32. , 29.4, 20.3, 24.4, 14.6, 19.5, 14.1, 14.3,
       15.6, 10.5,  6.3, 19.3, 19.3, 13.4, 36.4, 17.8, 13.5, 16.5,  8.3,
       14.3, 16. , 13.4, 28.6, 43.5, 20.2, 22. , 23. , 20.7, 12.5, 48.5,
       14.6, 13.4, 23.7, 50. , 21.7, 39.8, 38.7, 22.2, 34.9, 22.5, 31.1,
       28.7, 46. , 41.7, 21. , 26.6, 15. , 24.4, 13.3, 21.2, 11.7, 21.7,
       19.4, 50. , 22.8, 19.7, 24.7, 36.2, 14.2, 18.9, 18.3, 20.6, 24.6,
       18.2,  8.7, 44. , 10.4, 13.2, 21.2, 37. , 30.7, 22.9, 20. , 19.3,
       31.7, 32. , 23.1, 18.8, 10.9, 50. , 19.6,  5. , 14.4, 19.8, 13.8,
       19.6, 23.9, 24.5, 25. , 19.9, 17.2, 24.6, 13

In [112]:
print(y_test.shape)
print(y_test.size)
y_test

(102,)
102


array([ 7.2, 18.8, 19. , 27. , 22.2, 24.5, 31.2, 22.9, 20.5, 23.2, 18.6,
       14.5, 17.8, 50. , 20.8, 24.3, 24.2, 19.8, 19.1, 22.7, 12. , 10.2,
       20. , 18.5, 20.9, 23. , 27.5, 30.1,  9.5, 22. , 21.2, 14.1, 33.1,
       23.4, 20.1,  7.4, 15.4, 23.8, 20.1, 24.5, 33. , 28.4, 14.1, 46.7,
       32.5, 29.6, 28.4, 19.8, 20.2, 25. , 35.4, 20.3,  9.7, 14.5, 34.9,
       26.6,  7.2, 50. , 32.4, 21.6, 29.8, 13.1, 27.5, 21.2, 23.1, 21.9,
       13. , 23.2,  8.1,  5.6, 21.7, 29.6, 19.6,  7. , 26.4, 18.9, 20.9,
       28.1, 35.4, 10.2, 24.3, 43.1, 17.6, 15.4, 16.2, 27.1, 21.4, 21.5,
       22.4, 25. , 16.6, 18.6, 22. , 42.8, 35.1, 21.5, 36. , 21.9, 24.1,
       50. , 26.7, 25. ])