In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pt
import seaborn as sn
df=pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [86]:
df['Outcome']

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [87]:
x=df.drop('Outcome',axis=1)
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [88]:
y=df['Outcome']
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [89]:
y.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [90]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x=scaler.fit_transform(x)
x

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [91]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [92]:
x_train

array([[0.41176471, 0.75376884, 0.63934426, ..., 0.52459016, 0.26216909,
        0.55      ],
       [0.23529412, 0.48743719, 0.49180328, ..., 0.42026826, 0.1558497 ,
        0.01666667],
       [0.        , 0.82914573, 0.73770492, ..., 0.77943368, 0.14901793,
        0.03333333],
       ...,
       [0.23529412, 0.47236181, 0.53278689, ..., 0.3681073 , 0.02988898,
        0.        ],
       [0.64705882, 0.42713568, 0.60655738, ..., 0.4485842 , 0.09479078,
        0.23333333],
       [0.29411765, 0.68341709, 0.67213115, ..., 0.        , 0.23996584,
        0.8       ]])

In [93]:
x_train.shape

(614, 8)

In [94]:
y_train

603    1
118    0
247    0
157    0
468    1
      ..
763    0
192    1
629    0
559    0
684    0
Name: Outcome, Length: 614, dtype: int64

In [95]:
y_train.shape

(614,)

In [96]:
y_test

661    1
122    0
113    0
14     1
529    0
      ..
476    1
482    0
230    1
527    0
380    0
Name: Outcome, Length: 154, dtype: int64

In [97]:
y_test.shape

(154,)

In [98]:
x_test

array([[0.05882353, 1.        , 0.62295082, ..., 0.63934426, 0.56191289,
        0.01666667],
       [0.11764706, 0.53768844, 0.60655738, ..., 0.50074516, 0.13919727,
        0.03333333],
       [0.23529412, 0.38190955, 0.50819672, ..., 0.50670641, 0.13364646,
        0.06666667],
       ...,
       [0.23529412, 0.71356784, 0.70491803, ..., 0.6557377 , 0.24210077,
        0.01666667],
       [0.17647059, 0.58291457, 0.60655738, ..., 0.39195231, 0.01238258,
        0.05      ],
       [0.05882353, 0.53768844, 0.59016393, ..., 0.45901639, 0.31725021,
        0.05      ]])

In [99]:
x_test.shape

(154, 8)

# Cross Validation Methods

In [100]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [101]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.8181818181818182

In [102]:
SVM=SVC()
SVM.fit(x_train,y_train)
SVM.score(x_test,y_test)

0.7987012987012987

In [103]:
rt=RandomForestClassifier(n_estimators=40)
rt.fit(x_train,y_train)
rt.score(x_test,y_test)

0.7857142857142857

# K-Fold Method Cross-Validation

In [104]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [105]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [106]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [107]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

0.8181818181818182

In [108]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.7987012987012987

In [109]:
get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test)

0.7987012987012987

# StratifiedKFold Cross-Validation

In [110]:
from sklearn import datasets
import warnings
digits = datasets.load_digits()

In [111]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=5)
scores_l=[]
scores_SVM=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
                                  digits.target[train_index],digits.target[test_index]
    
print(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
print(get_score(SVC(),x_train,x_test,y_train,y_test))
print(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

C:\Users\91630\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9148580968280468
0.9549248747913188
0.9232053422370617


In [112]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=5)
scores_l=[]
scores_SVM=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
                                  digits.target[train_index],digits.target[test_index]
    
scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test)
scores_SVM.append(get_score(SVC(),x_train,x_test,y_train,y_test)
scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test)

SyntaxError: invalid syntax (2005693512.py, line 12)

In [113]:
scores_l

[]

In [114]:
scores_SVM

[]

In [115]:
scores_rf

[]

# Cross-Validation Scores

In [116]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),x,y)

array([0.77272727, 0.73376623, 0.77272727, 0.79084967, 0.77777778])

In [117]:
cross_val_score(SVC(),x,y)

array([0.77272727, 0.73376623, 0.75974026, 0.82352941, 0.79084967])

In [118]:
cross_val_score(RandomForestClassifier(n_estimators=40),x,y)

array([0.74025974, 0.74675325, 0.77272727, 0.82352941, 0.76470588])

In [119]:
cross_val_score(RandomForestClassifier(n_estimators=5),x,y)

array([0.71428571, 0.74025974, 0.79220779, 0.79084967, 0.74509804])

In [120]:
cross_val_score(RandomForestClassifier(n_estimators=60),x,y)

array([0.72077922, 0.74025974, 0.76623377, 0.84313725, 0.76470588])

In [121]:
cross_val_score(RandomForestClassifier(n_estimators=15),x,y)

array([0.72077922, 0.72077922, 0.71428571, 0.76470588, 0.74509804])

# Bagging

In [133]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
bm=BaggingClassifier(base_estimator=RandomForestClassifier(),n_estimators=40,max_samples=0.8,random_state=0)
bm.fit(x_train,y_train)

BaggingClassifier(base_estimator=RandomForestClassifier(), max_samples=0.8,
                  n_estimators=40, random_state=0)

In [135]:
bm.score(x_test,y_test)

0.9148580968280468

# Ada Boosting

In [147]:
from sklearn.ensemble import AdaBoostClassifier
rf=RandomForestClassifier()
ab=AdaBoostClassifier(n_estimators=40,base_estimator=rf,learning_rate=1)
ab.fit(x_train,y_train)

AdaBoostClassifier(base_estimator=RandomForestClassifier(), learning_rate=1,
                   n_estimators=40)

In [140]:
ab.score(x_test,y_test)

0.8764607679465777

# Gradient Boosting

In [152]:
from sklearn.ensemble import GradientBoostingRegressor
gr=GradientBoostingRegressor(max_depth=2,n_estimators=3,learning_rate=1)
m=gr.fit(x_train,y_train)
m

GradientBoostingRegressor(learning_rate=1, max_depth=2, n_estimators=3)

In [149]:
gr.score(x_test,y_test)

0.2562088076749308

# XGBoosting

In [164]:
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier

In [168]:
models=[]
models.append(('LogisticRegression',LogisticRegression()))
models.append(('KNN ',KNeighborsClassifier()))
models.append(('SVM',SVC()))
models.append(('XGBClassifier',XGBClassifier(eta=0.01,gamma=10)))
import time
results=[]
names=[]
scoring='Accuracy'
for name,model in models:
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    predict=[round(value) for value in y_pred]
    accuracy=metrics.accuracy_score(y_test,predict)
    print('Accuracy: %.2f%%' %(accuracy*100.0),name)
    #print('-------%s seconds-----' %(time.time() - start_time))

C:\Users\91630\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 91.49% LogisticRegression
Accuracy: 96.49% KNN 
Accuracy: 95.49% SVM
Accuracy: 81.80% XGBClassifier
