In [47]:
import pandas as pd
df=pd.read_csv('Tips.csv')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [53]:
x=df.drop('tip',axis=1)
y=df['tip']
x.head()

total_bill     sex smoker  day    time  size
0       16.99  Female     No  Sun  Dinner     2
1       10.34    Male     No  Sun  Dinner     3
2       21.01    Male     No  Sun  Dinner     3
3       23.68    Male     No  Sun  Dinner     2
4       24.59  Female     No  Sun  Dinner     4

In [54]:
y.head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [57]:
print(x_train.shape)
print(x_train.size)
x_train.head()

(195, 6)
1170


total_bill   sex smoker   day    time  size
7         26.88  Male     No   Sun  Dinner     4
83        32.68  Male    Yes  Thur   Lunch     2
176       17.89  Male    Yes   Sun  Dinner     2
106       20.49  Male    Yes   Sat  Dinner     2
156       48.17  Male     No   Sun  Dinner     6

In [58]:
print(x_test.shape)
print(x_test.size)
x_test.head()

(49, 6)
294


total_bill     sex smoker  day    time  size
64        17.59    Male     No  Sat  Dinner     3
63        18.29    Male    Yes  Sat  Dinner     4
55        19.49    Male     No  Sun  Dinner     2
111        7.25  Female     No  Sat  Dinner     1
225       16.27  Female    Yes  Fri   Lunch     2

In [60]:
print(y_train.shape)
print(y_train.size)
y_train.head()

(195,)
195


7      3.12
83     5.00
176    2.00
106    4.06
156    5.00
Name: tip, dtype: float64

In [61]:
print(y_test.shape)
print(y_test.size)
y_test.head()

(49,)
49


64     2.64
63     3.76
55     3.51
111    1.00
225    2.50
Name: tip, dtype: float64

In [63]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
pre=ColumnTransformer(transformers=[('num',StandardScaler(),['total_bill','size']),
                                    ('cat',OneHotEncoder(),['sex','smoker','day','time'])])
x_train=pre.fit_transform(x_train)
x_test=pre.transform(x_test)

In [65]:
x_train

array([[ 0.73240914,  1.48790007,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 1.36827467, -0.62221275,  0.        , ...,  1.        ,
         0.        ,  1.        ],
       [-0.25318243, -0.62221275,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-1.04691802, -0.62221275,  1.        , ...,  1.        ,
         0.        ,  1.        ],
       [ 1.33757772,  1.48790007,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-1.41966678, -0.62221275,  0.        , ...,  0.        ,
         1.        ,  0.        ]])

In [66]:
x_test

array([[-0.28607202,  0.43284366,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.20932963,  1.48790007,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.07777125, -0.62221275,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ],
       [-1.41966678, -1.67726916,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.43078625, -0.62221275,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ],
       [-1.58411476, -0.62221275,  1.        ,  0.        ,  0.        ,
         1.        ,  

In [69]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [71]:
lr.score(x_test,y_test)

0.5545031052534936

In [70]:
y_pred=lr.predict(x_test)
y_pred

array([2.75976768, 2.99712626, 2.81673204, 1.4632311 , 3.12654885,
       1.77482578, 2.54679105, 3.11359077, 2.88681115, 4.50140326,
       3.18428659, 3.17091975, 2.3527022 , 2.29224593, 2.87517409,
       4.16944264, 1.92603957, 2.24308317, 2.3679374 , 3.30322842,
       3.79547836, 2.84290839, 2.5417152 , 2.43574813, 2.32853543,
       2.58333477, 2.76729999, 4.59978345, 3.73195325, 2.40199442,
       2.31295548, 2.27962689, 2.46828159, 1.92661159, 2.71399481,
       2.30185826, 2.71063603, 2.09555601, 5.60088215, 3.34295006,
       2.25147162, 2.27534617, 2.56519997, 4.33905752, 2.11239476,
       2.81768662, 2.60608807, 2.99566606, 2.72262204])

In [72]:
from sklearn import metrics
metrics.r2_score(y_test,y_pred)

0.5545031052534936

In [132]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the column transformer to apply different transformers to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), [0, 1]),
        ('cat', OneHotEncoder(), [2, 3])
    ])

# Apply the column transformer to the training data
X_train_transformed = preprocessor.fit_transform(X_train)

# Apply the column transformer to the testing data
X_test_transformed = preprocessor.transform(X_test)

# Define the logistic regression model
lr = LogisticRegression()

# Fit the model on the transformed training data
lr.fit(X_train_transformed, y_train)

# Predict the classes of the testing data
y_pred = lr.predict(X_test_transformed)

# Evaluate the accuracy of the model
accuracy = lr.score(X_test_transformed, y_test)
print("Accuracy:", accuracy)


ValueError: Found unknown categories [3.6, 6.4, 6.9] in column 0 during transform

In [126]:
from sklearn import datasets
df=datasets.load_iris()
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [127]:
x=df.data
y=df.target
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [128]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [129]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [133]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), [0, 1]),
        ('cat', OneHotEncoder(), [2, 3])])
x_train_transformed = preprocessor.fit_transform(x_train)

In [134]:
x_train_transformed

<120x64 sparse matrix of type '<class 'numpy.float64'>'
	with 480 stored elements in Compressed Sparse Row format>