In [39]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [40]:
steps=[('Standard_scaler',StandardScaler()),('Classifier',LogisticRegression())]

In [41]:
steps

[('Standard_scaler', StandardScaler()), ('Classifier', LogisticRegression())]

In [42]:
Pipeline(steps)

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [46]:
pipe=Pipeline(steps)
pipe

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [44]:
#visalize the pipelines
from sklearn import set_config
set_config(display='diagram')
pipe

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [18]:
#creating a dataset
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000)
x.shape

(1000, 20)

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)
x_train

array([[ 0.54319334, -0.13956837,  0.69738177, ..., -0.52172049,
         0.79628794,  0.48603814],
       [ 0.76278101,  0.57309959,  1.22828691, ..., -0.72192639,
        -0.54300489, -0.33777545],
       [-0.38413932,  0.82086323, -0.90144775, ..., -0.9268574 ,
         0.19064004,  1.7338743 ],
       ...,
       [-0.35136168,  0.89395555, -1.08346534, ...,  0.1774577 ,
        -0.40800667,  1.16269118],
       [ 0.14001674, -0.64887523,  0.92057981, ..., -1.11926269,
        -0.0798119 ,  1.11013795],
       [-0.46597239, -0.70475851, -1.02165236, ..., -0.37887774,
        -0.72660157, -0.58004604]])

In [21]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('Classifier', LogisticRegression())])

In [22]:
y_pred=pipe.predict(x_test)
y_pred

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,

In [29]:
#Display a pipeline with standard scaler, dimensionality reduction and then estimator
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
steps=[('scaling',StandardScaler()),('PCA',PCA(n_components=3)),('SVC',SVC())]
Pipeline(steps)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [31]:
pipe2=Pipeline(steps)
pipe2['scaling'].fit_transform(x_train)

array([[ 0.54887757, -0.09742168,  0.57922553, ..., -0.84207427,
         0.80082427,  0.48765508],
       [ 0.7705309 ,  0.61366079,  0.97492118, ..., -1.16801727,
        -0.54792824, -0.34604446],
       [-0.38717851,  0.86087322, -0.61241839, ..., -1.50165295,
         0.19089856,  1.75046558],
       ...,
       [-0.35409254,  0.93380293, -0.74808022, ...,  0.29621508,
        -0.41197651,  1.17242813],
       [ 0.14190828, -0.60559547,  0.7455801 , ..., -1.81489627,
        -0.08146364,  1.11924424],
       [-0.46978139, -0.66135442, -0.70200961, ..., -0.60952071,
        -0.7328217 , -0.59122236]])

In [32]:
pipe2.fit(x_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [33]:
pipe2.predict(x_test)

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,

In [37]:
#Complex examples of columns transformer
from sklearn.impute import SimpleImputer
import numpy as np
numeric_processor=Pipeline(steps=[('imputation_mean',SimpleImputer(missing_values=np.mean,strategy='mean')),
                                 ('scaler',StandardScaler())])
numeric_processor

Pipeline(steps=[('imputation_mean',
                 SimpleImputer(missing_values=<function mean at 0x000001E3C1482280>)),
                ('scaler', StandardScaler())])

In [39]:
#categorical preprocessing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(steps=[('Imputation_constant',SimpleImputer(fill_value='missing',strategy='constant')),
                                         ('onehot',OneHotEncoder(handle_unknown='ignore'))])
categorical_processor

Pipeline(steps=[('Imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [43]:
#combien processing techniques
from sklearn.compose import ColumnTransformer
ColumnTransformer([
    ('Categorical',categorical_processor,['gender','city']),
    ('numeric',numeric_processor,['age','height'])])

ColumnTransformer(transformers=[('Categorical',
                                 Pipeline(steps=[('Imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numeric',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer(missing_values=<function mean at 0x000001E3C1482280>)),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [45]:
preprocessor=ColumnTransformer([
    ('Categorical',categorical_processor,['gender','city']),
    ('numeric',numeric_processor,['age','height'])])
preprocessor

ColumnTransformer(transformers=[('Categorical',
                                 Pipeline(steps=[('Imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numeric',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer(missing_values=<function mean at 0x000001E3C1482280>)),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [46]:
from sklearn.pipeline import make_pipeline
make_pipeline(preprocessor,LogisticRegression())

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('Categorical',
                                                  Pipeline(steps=[('Imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numeric',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer(missing_values=<function mean at 0x000001E3C1482280>)),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])

In [47]:
pipe=make_pipeline(preprocessor,LogisticRegression())
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('Categorical',
                                                  Pipeline(steps=[('Imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numeric',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer(missing_values=<function mean at 0x000001E3C1482280>)),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])

In [19]:
import warnings
warnings.filterwarnings('ignore')

In [20]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [22]:
df=pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [23]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [30]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,[0,1,2,3,4,5,6,7]],df.iloc[:,[8]],test_size=0.2,random_state=1)

In [33]:
x_train.shape

(614, 8)

In [34]:
y_train.shape

(614, 1)

In [37]:
LogisticRegressionPipeline=Pipeline([('my scaler',MinMaxScaler()),('my PCA',PCA(n_components=3)),
                                     ('logisitic_Regression',LogisticRegression())])


In [49]:
DecisionTreePipeline=Pipeline([('my scaler',MinMaxScaler()),('my PCA',PCA(n_components=3)),
                                     ('logisitic_Regression',DecisionTreeClassifier())])

In [50]:
RandomForestPipeline=Pipeline([('my scaler',MinMaxScaler()),('my PCA',PCA(n_components=3)),
                                     ('logisitic_Regression',RandomForestClassifier())])

In [51]:
mypipeline=[LogisticRegressionPipeline,DecisionTreePipeline,RandomForestPipeline]

In [52]:
accuracy=0.0
classifier=0
pipeline=""

In [53]:
PipelineDict={0:'Logistic Regression',1:'Decision Tree',2:'Random Forest'}

In [54]:
for mypipe in mypipeline:
    mypipe.fit(x_train,y_train)