In [41]:
import numpy as np
from numpy.linalg import eigh,norm
a=np.array([[-5,2,3],[-2,5,1],[-3,1,-5]])      # A= UD*VT
a

array([[-5,  2,  3],
       [-2,  5,  1],
       [-3,  1, -5]])

In [5]:
a.T@a

array([[ 38, -23,  -2],
       [-23,  30,   6],
       [ -2,   6,  35]])

In [6]:
eigh(a.T@a)

(array([10.20319535, 34.20677963, 58.59002502]),
 array([[-0.62582822,  0.25924852,  0.73561488],
        [-0.76812136, -0.04115132, -0.63898055],
        [ 0.13538324,  0.96493356, -0.22488798]]))

In [8]:
ev,V=eigh(a.T@a)
ev

array([10.20319535, 34.20677963, 58.59002502])

In [9]:
V

array([[-0.62582822,  0.25924852,  0.73561488],
       [-0.76812136, -0.04115132, -0.63898055],
       [ 0.13538324,  0.96493356, -0.22488798]])

In [14]:
print(V[:,0])
print(V[:,1])
print(V[:,2])

[-0.62582822 -0.76812136  0.13538324]
[ 0.25924852 -0.04115132  0.96493356]
[ 0.73561488 -0.63898055 -0.22488798]


In [19]:
u0=a@V[:,0]/norm(a@V[:,0])
u1=a@V[:,1]/norm(a@V[:,1])
u2=a@V[:,2]/norm(a@V[:,2])
print(u0)
print(u1)
print(u1)

[ 0.62582822 -0.76812136  0.13538324]
[ 0.25924852  0.04115132 -0.96493356]
[ 0.25924852  0.04115132 -0.96493356]


In [20]:
u=np.array([u0,u1,u1]).T
u

array([[ 0.62582822,  0.25924852,  0.25924852],
       [-0.76812136,  0.04115132,  0.04115132],
       [ 0.13538324, -0.96493356, -0.96493356]])

In [22]:
u.T @a @V

array([[ 3.19424410e+00,  4.22306026e-16,  2.15115964e-15],
       [ 3.27752437e-16,  5.84865622e+00, -1.37625106e-15],
       [ 3.27752437e-16,  5.84865622e+00, -1.37625106e-15]])

In [27]:
np.round(u.T @a @V )

array([[ 3.,  0.,  0.],
       [ 0.,  6., -0.],
       [ 0.,  6., -0.]])

In [29]:
np.round(u.T @a @V , decimals=2)

array([[ 3.19,  0.  ,  0.  ],
       [ 0.  ,  5.85, -0.  ],
       [ 0.  ,  5.85, -0.  ]])

In [33]:
np.round(u.T @a @V , decimals=5)

array([[ 3.19424,  0.     ,  0.     ],
       [ 0.     ,  5.84866, -0.     ],
       [ 0.     ,  5.84866, -0.     ]])

In [37]:
np.round(u.T @a @V , decimals=15)

array([[ 3.19424410e+00,  0.00000000e+00,  2.00000000e-15],
       [ 0.00000000e+00,  5.84865622e+00, -1.00000000e-15],
       [ 0.00000000e+00,  5.84865622e+00, -1.00000000e-15]])