In [4]:
#mean 
import statistics as st
data=[2,4,5,8,66,19,10]
x=st.mean(data)
print('mean is:',x)

mean is: 16.285714285714285


In [3]:
import numpy as np
import statistics as st
a=np.arange(4,40,4)
print(a)
x=st.mean(a)
print('mean is:',x)

[ 4  8 12 16 20 24 28 32 36]
mean is: 20


In [40]:
import statistics as st
n1=(2,4,6,7,8,9,10)
n2=(2,18,39,49,29,30,490)
n3=(5,299,494,205,302,44993)
print('mean of n1:',st.mean(n1))
#print('mean of n1:',st.pmean(n1))
print('mean of n2:',st.mean(n2))
print('mean of n3:',st.mean(n3))

mean of n1: 6.571428571428571
mean of n2: 93.85714285714286
mean of n3: 7716.333333333333


In [23]:
#ungrouped data in mean
def mean(lower_limit,upper_limit,freq,n):
    mid=[0.0]*n
    sum=0
    freqsum=0
    for i in range(0,n):
        mid[i]=((lower_limit[i]+upper_limit[i])/2)
        sum=sum+mid[i]*freq[i]
        freqsum=freqsum+freq[i]
lower_limit=[1,6,11,16,21]
upper_limit=[5,10,15,20,25]
freq=[10,20,30,40,50]
n=len(freq)
print(mean(lower_limit,upper_limit,freq,n))

None


In [28]:
#harmonic mean 
import statistics as st
import numpy as np
n1=np.arange(2,20,2)
n2=np.arange(3,20,2)
n3=np.arange(4,20,2)
print(n1)
print(n2)
print(n3)
print()
print('mean of n1 is:',st.harmonic_mean(n1))
print('mean of n2 is:',st.harmonic_mean(n2))
print('mean of n3 is:',st.harmonic_mean(n3))

[ 2  4  6  8 10 12 14 16 18]
[ 3  5  7  9 11 13 15 17 19]
[ 4  6  8 10 12 14 16 18]

mean of n1 is: 6.362743722822275
mean of n2 is: 7.941721668662724
mean of n3 is: 8.74810154046431


In [31]:
#geometric mean
import statistics as st
print('mean of data is:',st.harmonic_mean([10,20,30]))
print('mean of data is:',st.harmonic_mean([10,20,30,40,50,60]))

mean of data is: 16.363636363636363
mean of data is: 24.489795918367346


In [39]:
import statistics as st
import numpy as np
n1=np.arange(2,20,2)
n2=np.arange(3,20,2)
n3=np.arange(4,20,2)
print(n1)
print(n2)
print(n3)
print()
print('mean of n1 is:',st.geometric_mean(n1))
print('mean of n2 is:',st.geometric_mean(n2))
print('mean of n3 is:',st.geometric_mean(n3))

[ 2  4  6  8 10 12 14 16 18]
[ 3  5  7  9 11 13 15 17 19]
[ 4  6  8 10 12 14 16 18]

mean of n1 is: 8.294332548793825
mean of n2 is: 9.540308160689955
mean of n3 is: 9.908327999296404


In [4]:
#median
import statistics as st
import numpy as np
n1=np.arange(2,10,2)
n2=np.arange(3,10,3)
n3=np.arange(4,20,4)
print(n1)
print(n2)
print(n3)
print()
print('median of n1 is:',st.median(n1))
print('median of n2 is:',st.median(n2))
print('median of n3 is:',st.median(n3))

[2 4 6 8]
[3 6 9]
[ 4  8 12 16]

median of n1 is: 5.0
median of n2 is: 6
median of n3 is: 10.0


In [5]:
#mode
import statistics as st
import numpy as np
n1=np.arange(2,20,2)
n2=np.arange(3,20,2)
n3=np.arange(4,20,2)
print(n1)
print(n2)
print(n3)
print()
print('mode of n1 is:',st.geometric_mean(n1))
print('mode of n2 is:',st.geometric_mean(n2))
print('mode of n3 is:',st.geometric_mean(n3))

[ 2  4  6  8 10 12 14 16 18]
[ 3  5  7  9 11 13 15 17 19]
[ 4  6  8 10 12 14 16 18]

mode of n1 is: 8.294332548793825
mode of n2 is: 9.540308160689955
mode of n3 is: 9.908327999296404


In [41]:
#range
a=[5,402,29,20,39,381,29,39,10,28,38,15]
print(a)
print()
ranges=max(a)-min(a)
print('the range of the data is:',ranges)

[5, 402, 29, 20, 39, 381, 29, 39, 10, 28, 38, 15]

the range of the data is: 397


In [43]:
#percentile
sort=sorted(a)
print(sort)
print()
index=len(sort)*20
print('The percentile of the indexed value is:',index)

[5, 10, 15, 20, 28, 29, 29, 38, 39, 39, 381, 402]

The percentile of the indexed value is: 240


In [45]:
#varience
import numpy as np
a=np.arange(2,40,5)
print(a)
b=np.var(a)
#c=np.pvar(a)
print('The varience of the sample:',b)
#print(c)

[ 2  7 12 17 22 27 32 37]
The varience of the sample: 131.25


In [38]:
#varience
import statistics as st
l=[3,5,5,5,6,7,8,13,14,14,17,18]
print(l)
a=st.variance(l)
print('sample varience of data:',a)
b=st.pvariance(l)
print('population varience of data:',b)

[3, 5, 5, 5, 6, 7, 8, 13, 14, 14, 17, 18]
sample varience of data: 27.71969696969697
population varience of data: 25.40972222222222


In [47]:
#standard deviation
import numpy as np
l=[3,5,5,39,93,29,392,4,30,22,22,4,3,22,94]
a=np.std(l,ddof=1)
b=np.std(l)
print('sample standard deviation:',a)
print('the population of standard deviation:',b)

sample standard deviation: 98.8302055234609
the population of standard deviation: 95.47904947625362


In [48]:
import statistics as st
l=[3,5,5,6,7,8,13,14,14,17,18]
a=st.stdev(l)
print('sample standard deviation:',a)
b=st.pstdev(l)
print('Population of standard deviation:',b)

sample standard deviation: 5.310367218940701
Population of standard deviation: 5.063236478416116


In [56]:
#covarience
import numpy as np
a=[[1,2,3],[6,7,8]]
c1=np.cov(a)
c2=np.cov(a,bias=True)
print(c1)
print(c2)

[[1. 1.]
 [1. 1.]]
[[0.66666667 0.66666667]
 [0.66666667 0.66666667]]


In [61]:
import numpy as np
x=[98,87,90,85,95,75]
y=[15,12,10,16,16,7]
a=np.cov(x,y)
b=np.cov(x,y,bias=True)
print('population of covarience is:',a)
print()
print('sample of covarience is:',b)

population of covarience is: [[66.26666667 21.13333333]
 [21.13333333 13.46666667]]

sample of covarience is: [[55.22222222 17.61111111]
 [17.61111111 11.22222222]]


In [63]:
import numpy as np
x=[98,87,90,85,95,75]
y=[15,12,10,16,16,7]
a=np.cov(x,y)[0][1]
b=np.cov(x,y,bias=True)[0][1]
print('population of covarience is:',a)
print('sample of covarience is:',b)

population of covarience is: 21.133333333333336
sample of covarience is: 17.61111111111111


In [5]:
#spearman's rank correlation coefficient
import numpy as np
import pandas as pd
scores=[93,49,39,20,68,39,40]
hours=[2,4,2,4,5,3,1,8]
np.corr(scores,hours)

AttributeError: module 'numpy' has no attribute 'corr'

In [8]:
import scipy.stats as sta
x=[39,49,29,68,39]
y=[38,29,68,19,20]
print(sta.spearmanr(x,y))

SpearmanrResult(correlation=-0.8207826816681234, pvalue=0.08858700531354378)


In [12]:
import scipy.stats as sta
x=[39,49,29,68,39]
y=[38,29,68,19,20]
print(sta.spearmanr(x,y)[0])

-0.8207826816681234
