Basic Programns of CNN

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers,datasets,models
(x_train,y_train),(x_test,y_test)=datasets.cifar10.load_data()

170498071/170498071 [==============================] - 4s 0us/step


In [ ]:
print(x_train.shape)
print(x_train.size)
print()
print(x_test.shape)
print(x_test.size)

(50000, 32, 32, 3)
153600000

(10000, 32, 32, 3)
30720000


In [ ]:
print(y_train.shape)
print(y_train.size)
print()
print(y_test.shape)
print(y_test.size)

(50000, 1)
50000

(10000, 1)
10000


In [ ]:
x_train=x_train/255
x_test=x_test/255
print(x_train[1])

[[[0.60392157 0.69411765 0.73333333]
  [0.49411765 0.5372549  0.53333333]
  [0.41176471 0.40784314 0.37254902]
  ...
  [0.35686275 0.37254902 0.27843137]
  [0.34117647 0.35294118 0.27843137]
  [0.30980392 0.31764706 0.2745098 ]]

 [[0.54901961 0.62745098 0.6627451 ]
  [0.56862745 0.6        0.60392157]
  [0.49019608 0.49019608 0.4627451 ]
  ...
  [0.37647059 0.38823529 0.30588235]
  [0.30196078 0.31372549 0.24313725]
  [0.27843137 0.28627451 0.23921569]]

 [[0.54901961 0.60784314 0.64313725]
  [0.54509804 0.57254902 0.58431373]
  [0.45098039 0.45098039 0.43921569]
  ...
  [0.30980392 0.32156863 0.25098039]
  [0.26666667 0.2745098  0.21568627]
  [0.2627451  0.27058824 0.21568627]]

 ...

 [[0.68627451 0.65490196 0.65098039]
  [0.61176471 0.60392157 0.62745098]
  [0.60392157 0.62745098 0.66666667]
  ...
  [0.16470588 0.13333333 0.14117647]
  [0.23921569 0.20784314 0.22352941]
  [0.36470588 0.3254902  0.35686275]]

 [[0.64705882 0.60392157 0.50196078]
  [0.61176471 0.59607843 0.50980392]


In [ ]:
print(x_test[1])

[[[0.92156863 0.92156863 0.92156863]
  [0.90588235 0.90588235 0.90588235]
  [0.90980392 0.90980392 0.90980392]
  ...
  [0.91372549 0.91372549 0.91372549]
  [0.91372549 0.91372549 0.91372549]
  [0.90980392 0.90980392 0.90980392]]

 [[0.93333333 0.93333333 0.93333333]
  [0.92156863 0.92156863 0.92156863]
  [0.92156863 0.92156863 0.92156863]
  ...
  [0.9254902  0.9254902  0.9254902 ]
  [0.9254902  0.9254902  0.9254902 ]
  [0.92156863 0.92156863 0.92156863]]

 [[0.92941176 0.92941176 0.92941176]
  [0.91764706 0.91764706 0.91764706]
  [0.91764706 0.91764706 0.91764706]
  ...
  [0.92156863 0.92156863 0.92156863]
  [0.92156863 0.92156863 0.92156863]
  [0.91764706 0.91764706 0.91764706]]

 ...

 [[0.34117647 0.38823529 0.34901961]
  [0.16862745 0.2        0.14509804]
  [0.0745098  0.09019608 0.04313725]
  ...
  [0.6627451  0.72156863 0.70196078]
  [0.71372549 0.77254902 0.75686275]
  [0.7372549  0.79215686 0.78823529]]

 [[0.32156863 0.37647059 0.32156863]
  [0.18039216 0.22352941 0.14117647]


In [ ]:
print(y_train)

[[6]
 [9]
 [9]
 ...
 [9]
 [1]
 [1]]


In [ ]:
print(y_test)

[[3]
 [8]
 [8]
 ...
 [5]
 [1]
 [7]]


In [ ]:
#cnn models architecture
ml=models.Sequential()
ml.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
ml.add(layers.MaxPool2D((2,2)))
ml.add(layers.Conv2D(64, (3, 3), activation='relu'))
ml.add(layers.MaxPool2D((2,2)))
ml.add(layers.Conv2D(64,(2,2)))

In [ ]:
ml.add(layers.Flatten())
ml.add(layers.Dense(64,activation='relu'))
ml.add(layers.Dense(10))

In [ ]:
ml.compile(optimizer='adam',loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))

In [ ]:
ml.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test))

Epoch 1/10
1563/1563 [==============================] - 19s 5ms/step - loss: 1.4337 - val_loss: 1.1391
Epoch 2/10
1563/1563 [==============================] - 7s 4ms/step - loss: 1.0622 - val_loss: 0.9873
Epoch 3/10
1563/1563 [==============================] - 8s 5ms/step - loss: 0.9202 - val_loss: 0.9222
Epoch 4/10
1563/1563 [==============================] - 7s 5ms/step - loss: 0.8320 - val_loss: 0.9075
Epoch 5/10
1563/1563 [==============================] - 7s 4ms/step - loss: 0.7625 - val_loss: 0.8789
Epoch 6/10
1563/1563 [==============================] - 7s 5ms/step - loss: 0.7004 - val_loss: 0.9546
Epoch 7/10
1563/1563 [==============================] - 7s 5ms/step - loss: 0.6559 - val_loss: 0.8862
Epoch 8/10
1563/1563 [==============================] - 7s 5ms/step - loss: 0.6035 - val_loss: 0.9328
Epoch 9/10
1563/1563 [==============================] - 7s 4ms/step - loss: 0.5619 - val_loss: 0.9048
Epoch 10/10
1563/1563 [==============================] - 7s 5ms/step - loss: 0.51

In [ ]:
ml.predict(x_test)

313/313 [==============================] - 1s 2ms/step


array([[-3.3252742 , -1.8612862 ,  2.6932023 , ..., -6.117693  ,
        -0.8105299 , -5.624428  ],
       [ 3.8767211 , 14.45254   , -0.42761207, ..., -8.48079   ,
         8.506754  ,  5.7005463 ],
       [ 2.778866  ,  5.5669017 , -1.3296613 , ..., -5.8967123 ,
         4.3056245 ,  6.6943593 ],
       ...,
       [-3.9695601 , -4.1844587 ,  5.05785   , ...,  3.8431726 ,
        -1.6465722 , -0.28967953],
       [ 1.6745363 ,  1.7288017 , -0.9445181 , ..., -4.4577184 ,
        -8.745571  , -3.6174693 ],
       [-4.7966437 , -3.82441   ,  1.55962   , ..., 14.179976  ,
        -6.5114455 , -2.1316586 ]], dtype=float32)

In [ ]:
#loss and Accuracy
ml.evaluate(x_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.9645


0.9644755721092224

In [ ]:
#cnn models architecture
ml=models.Sequential()
ml.add(layers.Conv2D(32, (3, 3), activation='sigmoid', input_shape=(32, 32, 3)))
ml.add(layers.MaxPool2D((2,2)))
ml.add(layers.Conv2D(64, (3, 3), activation='relu'))
ml.add(layers.MaxPool2D((2,2)))
ml.add(layers.Conv2D(64,(2,2)))
#Flatten
ml.add(layers.Flatten())
ml.add(layers.Dense(64,activation='relu'))
ml.add(layers.Dense(10))

In [ ]:
from keras.layers import Dense
ml.compile(optimizer='adam',loss='binary_crossentropy')

In [ ]:
ml.fit(x_train,y_train,epochs=10,batch_size=8)

Epoch 1/10
6250/6250 [==============================] - 25s 4ms/step - loss: -41.0713
Epoch 2/10
6250/6250 [==============================] - 23s 4ms/step - loss: -41.0938
Epoch 3/10
6250/6250 [==============================] - 23s 4ms/step - loss: -41.0939
Epoch 4/10
6250/6250 [==============================] - 23s 4ms/step - loss: -41.0937
Epoch 5/10
6250/6250 [==============================] - 23s 4ms/step - loss: -41.0938
Epoch 6/10
6250/6250 [==============================] - 23s 4ms/step - loss: -41.0938
Epoch 7/10
6250/6250 [==============================] - 23s 4ms/step - loss: -41.0938
Epoch 8/10
6250/6250 [==============================] - 23s 4ms/step - loss: -41.0938
Epoch 9/10
6250/6250 [==============================] - 23s 4ms/step - loss: -41.0938
Epoch 10/10
6250/6250 [==============================] - 23s 4ms/step - loss: -41.0938


In [ ]:
ml.evaluate(x_test,y_test)